channels:
  - conda-forge
dependencies:
  - anyio
  - appnope
  - argon2-cffi
  - astroid
  - async_generator
  - attrs
  - autopep8
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - bleach
  - brotlipy
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - charset-normalizer
  - click
  - colorama
  - cryptography
  - cycler
  - cymem
  - cython-blis
  - dataclasses
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - flake8
  - freetype
  - icu
  - idna
  - importlib-metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - jbig
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter
  - jupyter-lsp
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab-lsp
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kiwisolver
  - lazy-object-proxy
  - lcms2
  - lerc
  - libblas
  - libcblas
  - libcxx
  - libdeflate
  - libffi
  - libgfortran
  - libgfortran5
  - libiconv
  - liblapack
  - libopenblas
  - libpng
  - libsodium
  - libtiff
  - libwebp-base
  - libxml2
  - libxslt
  - libzlib
  - llvm-openmp
  - lxml
  - lz4-c
  - markupsafe
  - matplotlib-base
  - matplotlib-inline
  - mccabe
  - mistune
  - murmurhash
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - nltk
  - notebook
  - numpy
  - olefile
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pathy
  - patsy
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pluggy
  - preshed
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - ptyprocess
  - pycodestyle
  - pycparser
  - pydantic
  - pydocstyle
  - pyflakes
  - pygments
  - pylint
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-lsp-jsonrpc
  - python-lsp-server
  - python_abi
  - pytrends
  - pytz
  - pyzmq
  - readline
  - regex
  - requests
  - requests-unixsocket
  - rope
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - shellingham
  - six
  - smart_open
  - sniffio
  - snowballstemmer
  - spacy-legacy
  - sqlite
  - statsmodels
  - terminado
  - testpath
  - threadpoolctl
  - tk
  - toml
  - tornado
  - tqdm
  - traitlets
  - typer
  - typing-extensions
  - typing_extensions
  - tzdata
  - ujson
  - urllib3
  - wasabi
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - wrapt
  - xz
  - yapf
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - catalogue
    - covid19dh
    - cython
    - gensim
    - plac
    - pmdarima
    - spacy
    - srsly
    - thinc
